import 'dart:io';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:zionsongs/feature/home/app_bar/pdf_export_service.dart';
import 'package:zionsongs/feature/home/hymn/hymn_models.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const pathProviderChannel = MethodChannel('plugins.flutter.io/path_provider');
  TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
      .setMockMethodCallHandler(pathProviderChannel, (call) async {
        if (call.method == 'getApplicationDocumentsDirectory') {
          final directory = Directory.systemTemp.createTempSync(
            'pdf-export-tests-app-docs',
          );
          return directory.path;
        }
        if (call.method == 'getTemporaryDirectory') {
          final directory = Directory.systemTemp.createTempSync(
            'pdf-export-tests-tmp',
          );
          return directory.path;
        }
        return null;
      });

  group('PdfExportService', () {
    test('preserves the caller-provided hymn order when building a PDF', () {
      final hymns = <LocalHymn>[
        LocalHymn()
          ..hymnId = 'h1'
          ..title = 'First',
        LocalHymn()
          ..hymnId = 'h2'
          ..title = 'Second',
        LocalHymn()
          ..hymnId = 'h3'
          ..title = 'Third',
      ];

      final ordered = PdfExportService.orderHymnsByIds(
        hymnIds: const ['h3', 'h1', 'h2'],
        hymns: hymns,
      );

      expect(ordered.map((h) => h.hymnId), equals(['h3', 'h1', 'h2']));
    });

    test('writes generated bytes to a safe app directory', () async {
      final service = PdfExportService();
      final pdfBytes = Uint8List.fromList([
        0x25,
        0x50,
        0x44,
        0x46,
        0x2D,
        0x31,
        0x2E,
        0x34,
      ]);

      final path = await service.writePdfToSafeDirectory(
        pdfBytes,
        fileName: 'unit_test.pdf',
      );

      final file = File(path);
      expect(await file.exists(), isTrue);
      expect(await file.length(), greaterThan(0));
    });

    test('builds HTML with embedded fonts and intact Indic text', () async {
      final service = PdfExportService();
      final hymns = <LocalHymn>[
        LocalHymn()
          ..hymnId = 'h1'
          ..title = 'Test hymn'
          ..hindiLyrics = 'हिंदी गीत'
          ..malayalamLyrics = 'മലയാളം പാട്ട്'
          ..englishLyrics = 'English lyrics',
      ];

      final html = await service.buildHymnHtml(hymns);

      expect(html, contains("font-family:Hindi"));
      expect(html, contains("font-family:Malayalam"));
      expect(html, contains('हिंदी गीत'));
      expect(html, contains('മലയാളം പാട്ട്'));
    });

    test(
      'uses packaged font URLs for the compact native HTML variant',
      () async {
        final html = await PdfExportService().buildHymnHtml([
          LocalHymn()
            ..hymnId = 'h1'
            ..title = 'Compact',
        ], embedFonts: false);

        expect(html, contains('assets/NotoSansDevanagari-Regular.ttf'));
        expect(html, contains('assets/NotoSansMalayalam-Regular.ttf'));
        expect(html, isNot(contains('data:font/ttf;base64')));
        expect(html.length, lessThan(10000));
      },
    );

    test('accepts only valid PDF bytes from the converter', () async {
      final service = PdfExportService(
        htmlConverter: (html, format) async => Uint8List.fromList([
          0x25,
          0x50,
          0x44,
          0x46,
          0x2D,
          0x31,
          0x2E,
          0x34,
        ]),
      );

      final pdfBytes = await service.generateHymnPdf([
        LocalHymn()
          ..hymnId = 'h1'
          ..title = 'Indic test'
          ..hindiLyrics = 'क्षमा प्रार्थना'
          ..malayalamLyrics = 'സ്തോത്രം',
      ]);

      expect(String.fromCharCodes(pdfBytes.take(4)), equals('%PDF'));
    });

    test('fails clearly when conversion returns invalid data', () async {
      final service = PdfExportService(
        htmlConverter: (html, format) async => Uint8List.fromList([1, 2, 3]),
      );

      expect(
        () => service.generateHymnPdf([
          LocalHymn()
            ..hymnId = 'h1'
            ..title = 'Invalid test',
        ]),
        throwsStateError,
      );
    });

    test('fails clearly when native conversion times out', () async {
      final service = PdfExportService(
        conversionTimeout: const Duration(milliseconds: 1),
        htmlConverter: (html, format) async {
          await Future<void>.delayed(const Duration(milliseconds: 20));
          return Uint8List.fromList([0x25, 0x50, 0x44, 0x46]);
        },
      );

      expect(
        () => service.generateHymnPdf([
          LocalHymn()
            ..hymnId = 'h1'
            ..title = 'Timeout test',
        ]),
        throwsStateError,
      );
    });

    test(
      'save action writes the generated PDF when the picker is unavailable',
      () async {
        final service = PdfExportService(
          htmlConverter: (html, format) async => Uint8List.fromList([
            0x25,
            0x50,
            0x44,
            0x46,
            0x2D,
            0x31,
            0x2E,
            0x34,
          ]),
        );
        final path = await service.saveHymnPdf(
          hymns: [
            LocalHymn()
              ..hymnId = 'h1'
              ..title = 'Saved hymn'
              ..hindiLyrics = 'हिंदी गीत'
              ..malayalamLyrics = 'മലയാളം പാട്ട്',
          ],
        );

        final file = File(path);
        expect(await file.exists(), isTrue);
        expect(
          String.fromCharCodes((await file.readAsBytes()).take(4)),
          equals('%PDF'),
        );
      },
    );

    test(
      'writes share PDFs to a temporary directory so they can be opened by the system share sheet',
      () async {
        final service = PdfExportService();
        final pdfBytes = Uint8List.fromList([
          0x25,
          0x50,
          0x44,
          0x46,
          0x2D,
          0x31,
          0x2E,
          0x34,
        ]);

        final path = await service.writePdfToSafeDirectory(
          pdfBytes,
          fileName: 'share_test.pdf',
          useTemporaryDirectory: true,
        );

        expect(path, contains('pdf-export-tests-tmp'));

        final file = File(path);
        expect(await file.exists(), isTrue);
        expect(await file.length(), greaterThan(0));
      },
    );

    test('rejects an empty hymn selection', () async {
      expect(
        () => PdfExportService().saveHymnPdf(hymns: const []),
        throwsStateError,
      );
    });
  });
}
