// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14u92ae9Ki2vtsXvvffEr0N2tfnVmCxc',
    appId: '1:1018034880390:web:13ba70710ac9f559e23607',
    messagingSenderId: '1018034880390',
    projectId: 'zion-songs-f03ad',
    authDomain: 'zion-songs-f03ad.firebaseapp.com',
    storageBucket: 'zion-songs-f03ad.firebasestorage.app',
    measurementId: 'G-08JNJCDLRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcOnPFOfwdxJuCr-fRM-SnUiNQO_G03A',
    appId: '1:1018034880390:android:8aed65b16fa76a8ee23607',
    messagingSenderId: '1018034880390',
    projectId: 'zion-songs-f03ad',
    storageBucket: 'zion-songs-f03ad.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjV9WgUZAZFfE2KSF6id6wDfSRruExsbw',
    appId: '1:1018034880390:ios:47966021c37d0612e23607',
    messagingSenderId: '1018034880390',
    projectId: 'zion-songs-f03ad',
    storageBucket: 'zion-songs-f03ad.firebasestorage.app',
    androidClientId: '1018034880390-di0imbk3apjant448u4gntvvcenkmegp.apps.googleusercontent.com',
    iosClientId: '1018034880390-lc65k30do89krtm279lmjfmonodsablg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zionsongs',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjV9WgUZAZFfE2KSF6id6wDfSRruExsbw',
    appId: '1:1018034880390:ios:47966021c37d0612e23607',
    messagingSenderId: '1018034880390',
    projectId: 'zion-songs-f03ad',
    storageBucket: 'zion-songs-f03ad.firebasestorage.app',
    androidClientId: '1018034880390-di0imbk3apjant448u4gntvvcenkmegp.apps.googleusercontent.com',
    iosClientId: '1018034880390-lc65k30do89krtm279lmjfmonodsablg.apps.googleusercontent.com',
    iosBundleId: 'com.example.zionsongs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD14u92ae9Ki2vtsXvvffEr0N2tfnVmCxc',
    appId: '1:1018034880390:web:8f4cecb3c71f3054e23607',
    messagingSenderId: '1018034880390',
    projectId: 'zion-songs-f03ad',
    authDomain: 'zion-songs-f03ad.firebaseapp.com',
    storageBucket: 'zion-songs-f03ad.firebasestorage.app',
    measurementId: 'G-61TVY1Y9Y0',
  );
}
